### ISSUE TITLE
Huanyang FC01 VFD (new model)

### ISSUE THREAD

**Issue by dresco** [grblHAL/Plugins_spindle#17]
A user of the H7 driver has one of these new Huanyang VFDs.

Has shared a manual [here](https://drive.google.com/file/d/1ClaLMfNDkWEd8mPnLNmg_PzwBDrnM0mc/view), appears to be Modbus RTU compliant, so I think it should work with @andrewmarles MODVFD spindle type..

I can take some guesses at the settings based on the manual, but wanted to open a ticket here to get some more eyes on it. I would imagine these are going to become more popular.

**VFD parameters (page 63).** 
Looks like it defaults to 19200 baud, even parity, 8 data bits, 1 stop bit.
From memory, grblHAL is expecting N,8,1 - so would need to change parameter P14.02 accordingly. 

**Modbus registers (page 84)**
$462 - Register for Run/stop (default value is 8192) - 8192 (0x2000)
$463 - Set Frequency Register (default value is 8193) - 8193 (0x2001)
$464 - Get Frequency Register (default value is 8451) - 12289 (0x3001)
$465 - Command word for CW (default value is 18) - 1
$466 - Command word for CCW (default value is 34) - 2
$467 - Command word for stop (default value is 1) - 5
$468 - RPM value multiplier for programming RPM (default value is 50) - 100?
$469 - RPM value divider for programming RPM (default value is 60) - 60?
$470 - RPM value multiplier for reading RPM (default value is 60) - ?
$471 - RPM value divider for reading RPM (default value is 100) - ?

Page 85 mentions settings P00.01, and P00.02 needed for Modbus control, although P00.02 is not listed anywhere else in manual?

**Comment by Avalonnw** [comment]
I can report that after changing P14.02 to 0 (N,8,1) VFD started making noises (fan turned on), all lights came on. Setting parameters 462-469 made it quiet again. Setting them to default values made it turn on the fan again. Nothing more. I'll have to investigate further tonight.

**Comment by terjeio** [comment]
There is a variable size mismatch in the spindleSetState() function for MODVFD, this can affect CW, CCW and stop commands if they are larger than 255. This was fixed in my main repo 20221013, build dates equal to or later than that should be ok.

**Comment by dresco** [comment]
> There is a variable size mismatch in the spindleSetState() function for MODVFD, this can affect CW, CCW and stop commands if they are larger than 255. This was fixed in my main repo 20221013, build dates equal to or later than that should be ok.

Thanks, have fallen a bit behind upstream. Will try to get the H7 repo updated this week..

**Comment by dresco** [comment]
fwiw, have updated the [H7 branch](https://github.com/dresco/STM32H7xx) & submodules this morning..

**Comment by Avalonnw** [comment]
Great news! Thanks!
Will check Tuesday (currently away)

**Comment by Avalonnw** [comment]
[Still no luck :(](https://github.com/dresco/STM32H7xx/issues/11#issuecomment-1465420684)

**Comment by terjeio** [comment]
[Solved](https://github.com/dresco/STM32H7xx/issues/11#issuecomment-1509668827) - closing this issue.
